stages:
  - test
  - release

lint:
  stage: test
  image: registry.gitlab.com/etke.cc/base/build
  script:
    - just lint

unit:
  stage: test
  image: registry.gitlab.com/etke.cc/base/build
  script:
    - just test

docker:
  stage: release
  only: ['main', 'tags']
  services:
    - docker:dind
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/jdrouet/docker-with-buildx:latest
  before_script:
    - apk --no-cache add git just --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
  script:
    - just login docker
  tags:
    - docker
