stages:
  - test
  - release
default:
  image: registry.gitlab.com/etke.cc/base/build
variables:
  PLATFORMS: linux/amd64

test:
  stage: test
  script:
    - 'just lint || echo "TODO: remove that once linter issue is fixed in the base/build image"'
    - just test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /root/cache/

docker:
  stage: release
  only: ['main', 'tags']
  services: ['docker:dind']
  script:
    - just login docker
