{
 "title": "Matrix Rooms Search",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Searching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Search Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mrs_search_queries)" }
   ]
  },
  {
   "title": "Search Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mrs_search_queries) by(api)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by server",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mrs_search_queries) by(server)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search queries by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mrs_search_queries{api=\"rest\"})",
     "legendFormat": "Web"
    },
    {
     "expr": "sum(mrs_search_queries{api=\"matrix\"})",
     "legendFormat": "Matrix"
    }
   ]
  },
  { "title": "Indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Online Servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mrs_servers_online" }
   ]
  },
  {
   "title": "Indexable Servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mrs_servers_indexable" }
   ]
  },
  {
   "title": "Indexable Servers %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mrs_servers_indexable/mrs_servers_online)*100"
    }
   ]
  },
  {
   "title": "Parsed Rooms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mrs_rooms_parsed" }
   ]
  },
  {
   "title": "Indexed Rooms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mrs_rooms_indexed" }
   ]
  },
  {
   "title": "Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "mrs_servers_online", "legendFormat": "Online" },
    { "expr": "mrs_servers_indexable", "legendFormat": "Indexable" }
   ]
  },
  {
   "title": "Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "mrs_rooms_parsed", "legendFormat": "Parsed" },
    { "expr": "mrs_rooms_indexed", "legendFormat": "Indexed" }
   ]
  }
 ]
}