openapi: 3.0.3
info:
  title: Matrix Rooms Search
  version: '0.x.x'
  description: 'Matrix Rooms Search service'
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.txt

externalDocs:
  description: Git repo
  url: https://gitlab.com/etke.cc/int/mrs
servers:
  - url: http://localhost:8080
    description: local
paths:
  /_health:
    get:
      tags:
        - public
      summary: Healthcheck endpoint
      description: check that service is alive
      operationId: health
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ok
                    example: 'ok'
  /stats:
    get:
      tags:
        - public
      summary: Statistics
      description: returns instance statistics
      operationId: stats
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  servers:
                    type: integer
                    description: Count of known servers
                    example: 3230
                  rooms:
                    type: integer
                    description: Count of parsed rooms
                    example: 3230
  /discover/{server_name}:
    post:
      tags:
        - public
      summary: Add a new server
      operationId: addServer
      parameters:
        - name: server_name
          in: path
          description: server name,domain
          required: true
          schema:
            type: string
            example: 'example.com'
      responses:
        '201':
          description: server has been added
        '208':
          description: server already discovered
        '422':
          description: server is not discoverable, check troubleshooting section of readme
        '429':
          description: too many requests, slow down.
        '500':
          description: something is wrong, check the logs
  /search:
    get:
      tags:
        - public
      summary: Search something!
      description: Search for matrix rooms
      operationId: search
      parameters:
        - name: q
          in: query
          description: search query
          required: true
          schema:
            type: string
        - name: l
          in: query
          description: limit
          required: false
          schema:
            type: integer
            default: 10
        - name: o
          in: query
          description: offset
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entry'
        '204':
          description: no results found.
  /-/status:
    get:
      tags:
        - private
      description: Get full status of the MRS
      operationId: admin_status
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      security:
       - admin:
  /-/servers:
    get:
      tags:
        - private
      description: Get YAML of the discovered (alive) matrix servers. Useful to adjust config file
      operationId: admin_servers
      responses:
        '200':
          description: successful operation
          content:
            application/x-yaml:
              schema:
                type: array
                items:
                  type: string
                  description: human-readable server name (matrix domain)
                  example: 'example.com'
      security:
       - admin:
  /-/discover:
    post:
      tags:
        - private
      description: Run matrix servers discovery process in background. If process already in progress, request will be ignored
      operationId: admin_discover
      responses:
        '201':
          description: request acknowledged
      security:
       - admin:
  /-/parse:
    post:
      tags:
        - private
      description: Runs matrix rooms parsing process in background. If process already in progress, request will be ignored
      operationId: admin_parse
      responses:
        '201':
          description: request acknowledged
      security:
       - admin:
  /-/reindex:
    post:
      tags:
        - private
      description: Runs parsed matrix rooms ingestion process in background. If process already in progress, request will be ignored
      operationId: admin_reindex
      responses:
        '201':
          description: request acknowledged
      security:
       - admin:
  /-/full:
    post:
      tags:
        - private
      description: Runs matrix servers discovery, then rooms parsing and ingestion in background. Useful when starting a fresh instance without any data. If process already in progress, request will be ignored
      operationId: admin_full
      responses:
        '201':
          description: request acknowledged
      security:
       - admin:

components:
  schemas:
    Entry:
      type: object
      properties:
        id:
          type: string
          description: room ID
          example: '!example:example.com'
        alias:
          type: string
          description: room alias
          example: '#example:example.com'
        name:
          type: string
          description: room name
          example: 'Example Room'
        topic:
          type: string
          description: room topic
          example: 'This is my topic'
        avatar:
          type: string
          description: MXC URI of room avatar
          example: 'mxc://example.com/sENrPlXsrqeJworlfatgzHmu'
        avatar_url:
          type: string
          description: HTTP URL of room avatar (use this one for web)
          example: 'https://matrix.example.com/_matrix/media/v3/download/example.com/sENrPlXsrqeJworlfatgzHmu'
        members:
          type: integer
          description: members count
          example: 9
        server:
          type: string
          description: server name
          example: example.com
        language:
          type: string
          description: 'ISO6391 language code (e.g. en, de, fr) OR `-` if there is not enough text in room name and topic to determine language'
          example: en
    Status:
      type: object
      properties:
        servers:
          type: integer
          description: amount of discovered servers
          example: 123
        rooms:
          type: integer
          description: amount of parsed rooms
          example: 321
        discovery:
          $ref: '#/components/schemas/ProcessStatus'
        parsing:
          $ref: '#/components/schemas/ProcessStatus'
        indexing:
          $ref: '#/components/schemas/ProcessStatus'
    ProcessStatus:
      type: object
      description: servers discovery info
      properties:
        started_at:
          type: string
          format: date-time
          description: start time of the process
          example: 2023-04-17T18:40:56Z
        finished_at:
          type: string
          format: date-time
          description: start time of the process
          example: 2023-04-17T18:40:56Z
  securitySchemes:
    admin:
      type: http
      scheme: basic
